version: 2
updates:
  - package-ecosystem: npm
    directory: /
    allow:
      - dependency-type: production
    labels:
      - dependency
    schedule:
      interval: weekly
      day: wednesday
      time: "12:00"
      timezone: "Canada/Mountain"
