# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Bug Report
description: Report that something is not working as expected.
labels:
  - Bug
body:
  - id: operating-system
    type: dropdown
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - id: version
    type: input
    attributes:
      label: Version
      placeholder: vX.Y.Z
    validations:
      required: true
  - id: reproduction-steps
    type: textarea
    attributes:
      label: Steps to Reproduce
      description: What you were trying to do that caused the issue.
      placeholder: |
        1. Do thing
        2. Do another thing
    validations:
      required: true
  - id: expected-results
    type: textarea
    attributes:
      label: Expected Results
      placeholder: |
        * Things happened!
    validations:
      required: true
  - id: actual-results
    type: textarea
    attributes:
      label: Actual Results
      placeholder: |
        * Things happened that shouldn't have!
    validations:
      required: true
  - id: additional-details
    type: textarea
    attributes:
      label: Additional Details
      description: Any extra information you think would be helpful.
    validations:
      required: false
  - id: acknowledgement
    type: checkboxes
    attributes:
      label: "I acknowledge that:"
      options:
        - label: I have searched for similar issues and found none.
          required: true
