name: Push
on:
  push:
jobs:
  push:
    name: Push
    permissions:
      contents: read
    strategy:
      matrix:
        build-os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
      fail-fast: true
    uses: ./.github/workflows/build.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    with:
      build-os: ${{matrix.build-os}}
